version: "3.1"

services:
  php-cli:
    image: algatux/php-cli-mongodb:1.0
    volumes:
        - ./:/home/user-dev/project
    tty: true
    depends_on:
      - mongo
    container_name: mb_php
  mongo:
    image: mongo:3.4.2
    ports:
      - 27017:27017
    entrypoint:
      - mongod
      - --quiet
      - --logpath=/dev/null
    container_name: mb_mongo
